In [1]:
import numpy as np
import pandas as pd

In [2]:
import ast

In [3]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies["keywords"]

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
                              ...
4798    [{"id": 5616, "name": "united states\u2013mexi...
4799                                                   []
4800    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4801                                                   []
4802    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4803, dtype: object

In [6]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
credits.shape

(4803, 4)

In [8]:
movies["status"].unique()

array(['Released', 'Post Production', 'Rumored'], dtype=object)

In [9]:
df = movies.merge(credits, on="title")

In [10]:
df.shape

(4809, 23)

In [11]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [15]:
df = df[["movie_id","genres", "overview", "title","keywords","cast","crew"]]

In [16]:
df.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
df.shape

(4809, 7)

In [18]:
df.isnull().sum()

movie_id    0
genres      0
overview    3
title       0
keywords    0
cast        0
crew        0
dtype: int64

In [19]:
df.dropna(inplace=True)

In [20]:
df.shape

(4806, 7)

In [21]:
df.duplicated().sum()

0

In [27]:
df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [25]:
df["genres"].head(1)

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [20]:
type(df["genres"].iloc[0])

str

In [21]:
def convert(obj):
    lis=[]
    for i in ast.literal_eval(obj):
        lis.append(i["name"])
    return lis

In [22]:
df["genres"] = df["genres"].apply(convert)

In [23]:
# Same Function with different method 
def converted2(data):
    l=[]
    new_data = ast.literal_eval(data)
    for i in (new_data):
        l.append(i["name"])
    return l

In [24]:
df.shape

(4806, 7)

In [28]:
df.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [25]:
df.head(5)

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
type(df["keywords"].iloc[0])

str

In [27]:
df["keywords"].iloc[0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [28]:
df["keywords"] = df["keywords"].apply(convert)

In [29]:
df.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [34]:
def same_as_converted(obj):
    i=0
    lis=[]
    while i<3:
        data=ast.literal_eval(obj)
        lis.append(data[i]["name"])
        i+=1

    return lis

In [30]:
df["cast"].iloc[1]

'[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]'

In [32]:
def converted(data):
    l=[]
    new_data = ast.literal_eval(data)
    for i in new_data[:3]:
        l.append(i["name"])
    return l

In [32]:
df["cast"].apply(converted)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, LÃ©a Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry BishÃ©, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [33]:
#2nd Method
def converted3(data):
    l=[]
    new_data = ast.literal_eval(data)
    counter=0
    for i in (new_data):
        if counter != 3:
            l.append(i["name"])
            counter+=1
        else:
            break
    return l

In [34]:
df["cast"]=df["cast"].apply(converted)

In [35]:
df.head(5)

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [36]:
df["crew"].iloc[0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [37]:
def fetch_director(obj):
    li=[]
    for i in ast.literal_eval(obj):
        if i["job"] == "Director":
            li.append(i["name"])
            break
    return li

In [38]:
df["crew"].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [39]:
df["crew"] = df["crew"].apply(fetch_director)

In [40]:
df.sample(5)

,movie_id,genres,overview,title,keywords,cast,crew
2909,357837,"[Drama, Romance]","This coming of age Dance Film, in the spirit o...",Dancin' It's On,"[dancing, competition, hotel, florida, dance t...","[Witney Carson, Chehon Wespi-Tschopp, Gary Dan...",[David Winters]
185,74,"[Adventure, Thriller, Science Fiction]",Ray Ferrier is a divorced dockworker and less-...,War of the Worlds,"[post traumatic stress disorder, new jersey, ...","[Tom Cruise, Dakota Fanning, Miranda Otto]",[Steven Spielberg]
1731,10383,"[Horror, Thriller]",A small group of Catholics led by an ailing pr...,Lost Souls,"[pedophilia, daughter, anti-christ, incest]","[Winona Ryder, Ben Chaplin, Sarah Wynter]",[Janusz KamiÅ„ski]
2372,12246,[History],The story recounts the early life of Genghis K...,Mongol: The Rise of Genghis Khan,"[mongolia, genghis khan]","[Tadanobu Asano, Sun Honglei, Khulan Chuluun]",[Sergei Bodrov]
1865,198185,[Drama],"In a last-ditch effort to save his career, spo...",Million Dollar Arm,"[baseball, sport, duringcreditsstinger]","[Jon Hamm, Bill Paxton, Lake Bell]",[Craig Gillespie]

In [41]:
df["overview"].iloc[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [42]:
df["overview"].apply(lambda x: x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [43]:
df["overview"] = df["overview"].apply(lambda x: x.split())

In [44]:
df.head(5)

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [45]:
def space_remover(obj):
    l=[]
    for i in (obj):
        i=i.replace(" ","")
        l.append(i)
    return l

In [46]:
df["crew"].apply(space_remover)

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [47]:
df["genres"].apply(space_remover)

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [48]:
df["cast"].apply(space_remover)

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LÃ©aSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishÃ©, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4806, dtype: object

In [49]:
df["genres"] = df["genres"].apply(space_remover)

In [50]:
df["keywords"] = df["keywords"].apply(space_remover)

In [51]:
df["cast"] = df["cast"].apply(space_remover)

In [52]:
df["crew"] = df["crew"].apply(space_remover)

In [53]:
df.head(5)

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [54]:
df["tags"] = df["overview"] + df["genres"] + df["keywords"] + df["cast"] + df["crew"]

In [55]:
df.head(5)

,movie_id,genres,overview,title,keywords,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [56]:
df = df.drop(columns=["genres","overview","keywords","cast","crew"])

In [57]:
df.head(5)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [58]:
df["tags"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [59]:
df["tags"] = df["tags"].apply(lambda x: " ".join(x))

In [60]:
df.head(5)

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [61]:
type(df["tags"][0])

str

In [62]:
df["tags"] = df["tags"].apply(lambda x: x.lower())

In [63]:
df.head(5)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [64]:
df["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [65]:
type(df["tags"][1])

str

In [66]:
import nltk

In [67]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [68]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [69]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [70]:
df["tags"]=df["tags"].apply(stem)

In [71]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

In [73]:
cv=CountVectorizer(max_features=5000, stop_words="english")

In [74]:
cv.fit_transform(df["tags"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [75]:
cv.fit_transform(df["tags"]).toarray().shape

(4806, 5000)

In [76]:
vectors = cv.fit_transform(df["tags"]).toarray()

In [77]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [78]:
from sklearn.metrics.pairwise import cosine_similarity

In [79]:
cosine_similarity(vectors)

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [80]:
cosine_similarity(vectors).shape

(4806, 4806)

In [81]:
similarity = cosine_similarity(vectors)

In [82]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [83]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [84]:
sorted(list(enumerate(similarity[0])), reverse=True,  key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255),
 (1202, 0.24455799402225925),
 (1192, 0.2367785320221084),
 (61, 0.23179316248638276),
 (778, 0.23174488732966073),
 (4046, 0.2278389747471728),
 (1916, 0.2252817784447915),
 (2782, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2329, 0.20443988269091456),
 (3606, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4190, 0.2029530274475215),
 (1440, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1087, 0.2020475485519274),
 (3671, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2969, 0.1925214071641298),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1199, 0.19088542889273336),
 (305, 0.19007487139298027),
 (4, 0.1892994097121204),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3325, 0.1860807318911967),
 (1273, 0.18394180184548975),
 (1327, 0.18394180184548975),
 (2997, 0.1813690625275029),
 (3997, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1069, 0.17954621161490197),
 (220, 0.1777046633277277),
 (184, 0.177343107178349),
 (1319, 0.17699808135119718),
 (168, 0.17521916101261562),
 (2200, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (36, 0.17316974359835272),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3536, 0.1711905958155815),
 (3160, 0.17040572913692198),
 (1978, 0.16943474841747155),
 (661, 0.1675415633166782),
 (529, 0.16742770563222897),
 (1827, 0.16742770563222897),
 (91, 0.16692446522239718),
 (41, 0.16563698349810535),
 (67, 0.16452254913212452),
 (150, 0.16426202236672155),
 (1533, 0.16222142113076254),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2511, 0.15907119074394446),
 (1176, 0.15789473684210528),
 (4008, 0.15737789507292674),
 (2727, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1379, 0.152008377581442),
 (111, 0.15018785229652767),
 (1342, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (513, 0.14843120879858804),
 (2071, 0.14808721943977307),
 (7, 0.14673479641335554),
 (2756, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1295, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1392, 0.14421498760030763),
 (1475, 0.1442149876003076),
 (1353, 0.14350946197048198),
 (1934, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3352, 0.1433848336691011),
 (1054, 0.1419745572840903),
 (1271, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1484, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2492, 0.1411956236812263),
 (95, 0.14048787173725413),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3407, 0.1391037210186643),
 (1961, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1325, 0.13834289277321493),
 (3779, 0.13834289277321493),
 (72, 0.13710212427677043),
 (843, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2165, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3980, 0.13530201829834768),
 (1804, 0.13518451760896877),
 (4348, 0.13497638119975428),
 (1320, 0.13476498501489081),
 (158, 0.13369695534647594),
 (502, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1556, 0.13334518676566626),
 (1369, 0.1324532357065044),
 (2374, 0.1324532357065044),
 (2580, 0.1324532357065044),
 (4077, 0.13157894736842107),
 (2129, 0.13124359177794215),
 (1013, 0.12988108336653278),
 (2177, 0.12988108336653278),
 (3620, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1770, 0.12977713690461004),
 (2869, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (369, 0.12824729401064427),
 (1084, 0.12824729401064427),
 (2682, 0.12824729401064427),
 (4228, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2968, 0.12725695259515557),
 (937, 0.126673647984535),
 (2476, 0.12565617248750865),
 (1737, 0.12565617248750863),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2446, 0.12515654358043973),
 (3626, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1094, 0.12487810821089254),
 (1156, 0.12487810821089254),
 (2648, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (3374, 0.12262786789699316),
 (1874, 0.12262786789699313),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1297, 0.12227899701112963),
 (2327, 0.12166606584807191),
 (2670, 0.12166606584807191),
 (3081, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1002, 0.1204950466257556),
 (1272, 0.1204950466257556),
 (1654, 0.1204950466257556),
 (1000, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3233, 0.11959121830873498),
 (1045, 0.11846977555181847),
 (1829, 0.11846977555181847),
 (2056, 0.11846977555181847),
 (2737, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (3719, 0.11803342130469506),
 (1669, 0.11803342130469505),
 (1711, 0.11803342130469505),
 (2785, 0.11803342130469505),
 (3998, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (454, 0.11707322644771176),
 (1613, 0.11707322644771176),
 (2280, 0.11707322644771176),
 (28, 0.116543309349613),
 (122, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (2543, 0.11587244366483038),
 (1493, 0.11551284429847784),
 (3210, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1218, 0.1147078669352809),
 (236, 0.11470786693528087),
 (1299, 0.11470786693528087),
 (85, 0.1141270638770543),
 (432, 0.11357771260606365),
 (1414, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1612, 0.11295649894498103),
 (123, 0.1124803176664619),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3145, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1346, 0.11164843913471803),
 (1571, 0.11164843913471803),
 (2368, 0.11141412945539662),
 (3307, 0.11141412945539662),
 (1508, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1570, 0.11020775375559674),
 (3426, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1029, 0.10968169942141635),
 (1941, 0.10968169942141635),
 (2144, 0.10968169942141635),
 (3006, 0.10968169942141635),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1520, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (740, 0.10838874619051501),
 (3091, 0.10838874619051501),
 (3628, 0.10838874619051501),
 (786, 0.10814761408717502),
 (3496, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1235, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1164, 0.10619884881071831),
 (1497, 0.10619884881071831),
 (1741, 0.10619884881071831),
 (2157, 0.10619884881071831),
 (2630, 0.10619884881071831),
 (4133, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1492, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (2068, 0.10526315789473685),
 (3338, 0.10526315789473685),
 (2494, 0.10471347707292386),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1193, 0.10390486669322622),
 (1767, 0.10390486669322622),
 (2813, 0.10390486669322622),
 (654, 0.10385162309931599),
 (2435, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (624, 0.1037571695799112),
 (2319, 0.1037571695799112),
 (2452, 0.1037571695799112),
 (2517, 0.1037571695799112),
 (3053, 0.1037571695799112),
 (3619, 0.1037571695799112),
 (3837, 0.1037571695799112),
 (1451, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1080, 0.10259783520851541),
 (3150, 0.10259783520851541),
 (3632, 0.10259783520851541),
 (3753, 0.10259783520851541),
 (3872, 0.10259783520851541),
 (4095, 0.10259783520851541),
 (2102, 0.10218988991416095),
 (2758, 0.10147651372376076),
 (3659, 0.10147651372376076),
 (3952, 0.10147651372376076),
 (3439, 0.10138838820672659),
 (508, 0.101338918387628),
 (1292, 0.101338918387628),
 (2243, 0.10133891838762799),
 (1401, 0.10060545457319173),
 (1435, 0.10060545457319173),
 (2095, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (986, 0.10012523486435178),
 (1035, 0.10012523486435178),
 (1610, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1075, 0.09933992677987831),
 (1278, 0.09933992677987831),
 (1880, 0.09933992677987831),
 (2049, 0.09933992677987831),
 (4016, 0.09933992677987831),
 (4196, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3618, 0.0989541391990587),
 (3781, 0.0989541391990587),
 (3933, 0.0989541391990587),
 (1771, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1107, 0.0978231976089037),
 (1397, 0.0978231976089037),
 (1819, 0.0978231976089037),
 (2249, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1154, 0.09733285267845754),
 (1723, 0.09733285267845754),
 (1938, 0.09733285267845754),
 (2783, 0.09733285267845754),
 (4254, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2237, 0.09567297464698798),
 (2552, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (791, 0.09544271444636668),
 (1569, 0.09544271444636668),
 (2558, 0.09544271444636668),
 (4201, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (978, 0.09365858115816941),
 (1274, 0.09365858115816941),
 (1355, 0.09365858115816941),
 (1470, 0.09365858115816941),
 (1682, 0.09365858115816941),
 (1688, 0.09365858115816941),
 (1717, 0.09365858115816941),
 (2392, 0.09365858115816941),
 (2484, 0.09365858115816941),
 (2588, 0.09365858115816941),
 (2641, 0.09365858115816941),
 (2646, 0.09365858115816941),
 (2816, 0.09365858115816941),
 (3535, 0.09365858115816941),
 (3718, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (301, 0.09365858115816939),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1442, 0.09269795493186431),
 (1697, 0.09269795493186431),
 (3405, 0.09269795493186431),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (1752, 0.09197090092274487),
 (2089, 0.09197090092274487),
 (2647, 0.09197090092274487),
 (3734, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (239, 0.09125667909262308),
 (2566, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (995, 0.09086217008485092),
 (1231, 0.09086217008485092),
 (1842, 0.09086217008485092),
 (3879, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1304, 0.09037128496931669),
 (1476, 0.09037128496931669),
 (2247, 0.09037128496931669),
 (2955, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2359, 0.08998425413316952),
 (2792, 0.08998425413316952),
 (2852, 0.08998425413316952),
 (3387, 0.08998425413316952),
 (3441, 0.08998425413316952),
 (3460, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1902, 0.0891313035643173),
 (2111, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1025, 0.08885233166386385),
 (2656, 0.08885233166386385),
 (2864, 0.08885233166386385),
 (3320, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1779, 0.08830215713766959),
 (2105, 0.08830215713766959),
 (2709, 0.08830215713766959),
 (2736, 0.08830215713766959),
 (3551, 0.08830215713766959),
 (479, 0.08797691788472335),
 (752, 0.08749572785196143),
 (1828, 0.08749572785196143),
 (2444, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1247, 0.08740748201220976),
 (1257, 0.08740748201220976),
 (3446, 0.08740748201220976),
 (3447, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1526, 0.08671099695241201),
 (2876, 0.08671099695241201),
 (3554, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1374, 0.08603090020146065),
 (2579, 0.08603090020146065),
 (3133, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (1017, 0.08594700851870801),
 (2350, 0.08594700851870801),
 (32, 0.08520286456846099),
 (217, 0.08520286456846099),
 (142, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1095, 0.08471737420873576),
 (1140, 0.08471737420873576),
 (1585, 0.08471737420873576),
 (2300, 0.08471737420873576),
 (4560, 0.08471737420873576),
 (48, 0.08447772061910234),
 (190, 0.08447772061910234),
 (1303, 0.08447772061910234),
 (1635, 0.08447772061910234),
 (2966, 0.08447772061910234),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (534, 0.0837707816583391),
 (1694, 0.0837707816583391),
 (3178, 0.0837707816583391),
 (3216, 0.0837707816583391),
 (3976, 0.0837707816583391),
 (4737, 0.0837707816583391),
 (1, 0.08346223261119858),
 (152, 0.08346223261119858),
 (203, 0.08346223261119858),
 (315, 0.08346223261119858),
 (547, 0.08346223261119858),
 (1684, 0.08346223261119858),
 (2124, 0.08346223261119858),
 (2382, 0.08321783316232578),
 (19, 0.0830812984794528),
 (403, 0.0830812984794528),
 (3903, 0.0830812984794528),
 (45, 0.08240856434303293),
 (2199, 0.08240856434303293),
 (39, 0.08226127456606226),
 (227, 0.08226127456606226),
 (341, 0.08226127456606226),
 (626, 0.08226127456606226),
 (787, 0.08226127456606226),
 (1205, 0.08226127456606226),
 (1745, 0.08226127456606226),
 (2163, 0.08226127456606226),
 (2657, 0.08226127456606226),
 (3138, 0.08226127456606226),
 (3299, 0.08226127456606226),
 (3468, 0.08226127456606226),
 (63, 0.08175191193132876),
 (501, 0.08175191193132876),
 (38, 0.08111071056538127),
 (242, 0.08111071056538127),
 (245, 0.08111071056538127),
 (306, 0.08111071056538127),
 (584, 0.08111071056538127),
 (812, 0.08111071056538127),
 (866, 0.08111071056538127),
 (901, 0.08111071056538127),
 (1267, 0.08111071056538127),
 (1515, 0.08111071056538127),
 (1660, 0.08111071056538127),
 (2335, 0.08111071056538127),
 (2640, 0.08111071056538127),
 (2667, 0.08111071056538127),
 (2861, 0.08111071056538127),
 (2873, 0.08111071056538127),
 (3525, 0.08111071056538127),
 (3924, 0.08111071056538127),
 (4492, 0.08111071056538127),
 (4568, 0.08111071056538127),
 (4626, 0.08111071056538127),
 (4641, 0.08111071056538127),
 (4654, 0.08111071056538127),
 (4657, 0.08111071056538127),
 (51, 0.08048436365855338),
 (164, 0.08000711205939975),
 (854, 0.08000711205939975),
 (899, 0.08000711205939975),
 (1323, 0.08000711205939975),
 (1743, 0.08000711205939975),
 (2679, 0.08000711205939975),
 (3762, 0.08000711205939975),
 (3814, 0.08000711205939975),
 (3849, 0.08000711205939975),
 (486, 0.07992075789278004),
 (103, 0.07987230638308718),
 (222, 0.07987230638308718),
 (1530, 0.07987230638308718),
 (2788, 0.07987230638308718),
 (4506, 0.07987230638308718),
 (1894, 0.0792740035289418),
 (16, 0.07894736842105264),
 (37, 0.07894736842105264),
 (241, 0.07894736842105264),
 (329, 0.07894736842105264),
 (1078, 0.07894736842105264),
 (1159, 0.07894736842105264),
 (2291, 0.07894736842105264),
 (3231, 0.07894736842105264),
 (4316, 0.07894736842105264),
 (193, 0.07878168645790681),
 (153, 0.07868894753646337),
 (776, 0.07868894753646337),
 (1043, 0.07868894753646337),
 (1824, 0.07868894753646337),
 (1922, 0.07868894753646337),
 (3726, 0.07868894753646337),
 (3830, 0.07868894753646337),
 (4279, 0.07868894753646337),
 (4473, 0.07868894753646337),
 (125, 0.07843304784240032),
 (286, 0.0781166566864507),
 (1655, 0.0781166566864507),
 (174, 0.07792865001991967),
 (402, 0.07792865001991967),
 (922, 0.07792865001991967),
 (1111, 0.07792865001991967),
 (2936, 0.07792865001991967),
 (3026, 0.07792865001991967),
 (3089, 0.07792865001991967),
 (3100, 0.07792865001991967),
 (3162, 0.07792865001991967),
 (4341, 0.07792865001991967),
 (1920, 0.07755667343294813),
 (3558, 0.07755667343294813),
 (1280, 0.0770085628656519),
 (40, 0.07694837640638656),
 (96, 0.07694837640638656),
 (101, 0.07694837640638656),
 (112, 0.07694837640638656),
 (207, 0.07694837640638656),
 (632, 0.07694837640638656),
 (737, 0.07694837640638656),
 (1287, 0.07694837640638656),
 (2215, 0.07694837640638656),
 (4266, 0.07694837640638656),
 (4624, 0.07694837640638656),
 (850, 0.07647191129018727),
 (1003, 0.07647191129018727),
 (1137, 0.07647191129018727),
 (1252, 0.07647191129018727),
 (1617, 0.07647191129018727),
 (2161, 0.07647191129018727),
 (2270, 0.07647191129018727),
 (2708, 0.07647191129018727),
 (3428, 0.07647191129018727),
 (4163, 0.07647191129018727),
 (70, 0.076004188790721),
 (82, 0.076004188790721),
 (235, 0.076004188790721),
 (349, 0.076004188790721),
 (492, 0.076004188790721),
 (1288, 0.076004188790721),
 (1519, 0.076004188790721),
 (2445, 0.076004188790721),
 (2914, 0.076004188790721),
 (4558, 0.076004188790721),
 (246, 0.07594632491572426),
 (2001, 0.07543142864047142),
 (3329, 0.07530940414109724),
 (98, 0.07509392614826384),
 (210, 0.07509392614826384),
 (361, 0.07509392614826384),
 (365, 0.07509392614826384),
 (503, 0.07509392614826384),
 (540, 0.07509392614826384),
 (680, 0.07509392614826384),
 (1007, 0.07509392614826384),
 (1291, 0.07509392614826384),
 (2159, 0.07509392614826384),
 (4043, 0.07509392614826384),
 (4203, 0.07509392614826384),
 (2252, 0.07492686492653551),
 (205, 0.07443229275647868),
 (800, 0.07443229275647868),
 (993, 0.07443229275647868),
 (1321, 0.07443229275647868),
 (1517, 0.07443229275647868),
 (1766, 0.07443229275647868),
 (2322, 0.07443229275647868),
 (2547, 0.07443229275647868),
 (2797, 0.07443229275647868),
 (3067, 0.07443229275647868),
 (3115, 0.07443229275647868),
 (3124, 0.07443229275647868),
 (4009, 0.07443229275647868),
 (4412, 0.07443229275647868),
 (4542, 0.07443229275647868),

In [85]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [86]:
def recommended(movies):
    movies_index = df[df["title"]==movies].index[0]
    distance = similarity[movies_index]
    movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(df.iloc[i[0]].title)

In [87]:
recommended("April Fool's Day")

Deterrence
A History of Violence
A Cinderella Story
Boynton Beach Club
Larry Crowne

In [88]:
df[df["title"]=="Kick-Ass 2"].index[0]

1742

In [89]:
df.iloc[65].title

'The Dark Knight'

In [90]:
df.sample(10)

,movie_id,title,tags
1581,59436,Midnight in Paris,a romant comedi about a famili travel to the f...
404,1904,Memoirs of a Geisha,a sweep romant epic set in japan in the year b...
472,4442,The Brothers Grimm,"folklor collector and con artists, jake and wi..."
743,6435,Practical Magic,"salli and gillian owens, born into a magic fam..."
1926,15992,Abandon,a psycholog thriller about a senior at one of ...
2265,10353,The Visitors II: The Corridors of Time,the sequel to the visitor reunit us with those...
1968,11635,Old School,three friend attempt to recaptur their glori d...
948,10393,The Replacements,maverick old-guard coach jimmi mcginti is hire...
3516,244783,Song One,"estrang from her family, franni return home wh..."
3965,170480,The Deported,an italian-american actor is deport to mexico ...

In [91]:
import pickle

In [92]:
pickle.dump(df,open("movies.pkl", "wb"))

In [93]:
pickle.dump(similarity, open("similarity.pkl","wb"))